//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plataforma_PAR.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ReceptorSoap")]
    public interface ReceptorSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Plataforma_PAR.ServiceReference1.HelloWorldResponse HelloWorld(Plataforma_PAR.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Plataforma_PAR.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Plataforma_PAR.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name scanIPSResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/scanIPS", ReplyAction="*")]
        Plataforma_PAR.ServiceReference1.scanIPSResponse scanIPS(Plataforma_PAR.ServiceReference1.scanIPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/scanIPS", ReplyAction="*")]
        System.Threading.Tasks.Task<Plataforma_PAR.ServiceReference1.scanIPSResponse> scanIPSAsync(Plataforma_PAR.ServiceReference1.scanIPSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Plataforma_PAR.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Plataforma_PAR.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Plataforma_PAR.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Plataforma_PAR.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class scanIPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="scanIPS", Namespace="http://tempuri.org/", Order=0)]
        public Plataforma_PAR.ServiceReference1.scanIPSRequestBody Body;
        
        public scanIPSRequest() {
        }
        
        public scanIPSRequest(Plataforma_PAR.ServiceReference1.scanIPSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class scanIPSRequestBody {
        
        public scanIPSRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class scanIPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="scanIPSResponse", Namespace="http://tempuri.org/", Order=0)]
        public Plataforma_PAR.ServiceReference1.scanIPSResponseBody Body;
        
        public scanIPSResponse() {
        }
        
        public scanIPSResponse(Plataforma_PAR.ServiceReference1.scanIPSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class scanIPSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string scanIPSResult;
        
        public scanIPSResponseBody() {
        }
        
        public scanIPSResponseBody(string scanIPSResult) {
            this.scanIPSResult = scanIPSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReceptorSoapChannel : Plataforma_PAR.ServiceReference1.ReceptorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReceptorSoapClient : System.ServiceModel.ClientBase<Plataforma_PAR.ServiceReference1.ReceptorSoap>, Plataforma_PAR.ServiceReference1.ReceptorSoap {
        
        public ReceptorSoapClient() {
        }
        
        public ReceptorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReceptorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReceptorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Plataforma_PAR.ServiceReference1.HelloWorldResponse Plataforma_PAR.ServiceReference1.ReceptorSoap.HelloWorld(Plataforma_PAR.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Plataforma_PAR.ServiceReference1.HelloWorldRequest inValue = new Plataforma_PAR.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Plataforma_PAR.ServiceReference1.HelloWorldRequestBody();
            Plataforma_PAR.ServiceReference1.HelloWorldResponse retVal = ((Plataforma_PAR.ServiceReference1.ReceptorSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Plataforma_PAR.ServiceReference1.HelloWorldResponse> Plataforma_PAR.ServiceReference1.ReceptorSoap.HelloWorldAsync(Plataforma_PAR.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Plataforma_PAR.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Plataforma_PAR.ServiceReference1.HelloWorldRequest inValue = new Plataforma_PAR.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Plataforma_PAR.ServiceReference1.HelloWorldRequestBody();
            return ((Plataforma_PAR.ServiceReference1.ReceptorSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Plataforma_PAR.ServiceReference1.scanIPSResponse Plataforma_PAR.ServiceReference1.ReceptorSoap.scanIPS(Plataforma_PAR.ServiceReference1.scanIPSRequest request) {
            return base.Channel.scanIPS(request);
        }
        
        public string scanIPS() {
            Plataforma_PAR.ServiceReference1.scanIPSRequest inValue = new Plataforma_PAR.ServiceReference1.scanIPSRequest();
            inValue.Body = new Plataforma_PAR.ServiceReference1.scanIPSRequestBody();
            Plataforma_PAR.ServiceReference1.scanIPSResponse retVal = ((Plataforma_PAR.ServiceReference1.ReceptorSoap)(this)).scanIPS(inValue);
            return retVal.Body.scanIPSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Plataforma_PAR.ServiceReference1.scanIPSResponse> Plataforma_PAR.ServiceReference1.ReceptorSoap.scanIPSAsync(Plataforma_PAR.ServiceReference1.scanIPSRequest request) {
            return base.Channel.scanIPSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Plataforma_PAR.ServiceReference1.scanIPSResponse> scanIPSAsync() {
            Plataforma_PAR.ServiceReference1.scanIPSRequest inValue = new Plataforma_PAR.ServiceReference1.scanIPSRequest();
            inValue.Body = new Plataforma_PAR.ServiceReference1.scanIPSRequestBody();
            return ((Plataforma_PAR.ServiceReference1.ReceptorSoap)(this)).scanIPSAsync(inValue);
        }
    }
}
